myapp/urls.py
from django.urls import path

from .views import *

urls = [
    # Misc
    ('', home, 'home'),
    ('settings', PasswordChange.as_view(), 'settings'),
    # User
    ('login', Login.as_view(), 'login'),
    ('demo', Login.as_view(guest_login=True), 'demo'),
    ('logout', Logout.as_view(), 'logout'),
    # Project
    ('projects', ProjectList.as_view(), 'project-list'),
    ('projects/create', ProjectCreate.as_view(), 'project-create'),
    ('projects/<int:p_id>/dashboard', ProjectDetail.as_view(), 'project-detail'),
    ('projects/<int:p_id>/update', ProjectUpdate.as_view(), 'project-update'),
    ('projects/<int:p_id>/delete', ProjectDelete.as_view(), 'project-delete'),
    # Sprint
    ('projects/<int:p_id>/sprints', SprintList.as_view(), 'sprint-list'),
    ('projects/<int:p_id>/sprints/create', SprintCreate.as_view(), 'sprint-create'),
    ('projects/<int:p_id>/sprints/<int:s_id>/board', SprintBoard.as_view(), 'sprint-board'),
    ('projects/<int:p_id>/sprints/<int:s_id>/chart', SprintChart.as_view(), 'sprint-chart'),
    ('projects/<int:p_id>/sprints/<int:s_id>/update', SprintUpdate.as_view(), 'sprint-update'),
    ('projects/<int:p_id>/sprints/<int:s_id>/delete', SprintDelete.as_view(), 'sprint-delete'),
    # Task
    ('projects/<int:p_id>/tasks', TaskList.as_view(), 'task-list'),
    ('projects/<int:p_id>/tasks/create', TaskCreate.as_view(), 'task-create'),
    ('projects/<int:p_id>/tasks/<int:t_id>/update', TaskUpdate.as_view(), 'task-update'),
    ('projects/<int:p_id>/tasks/<int:t_id>/delete', TaskDelete.as_view(), 'task-delete'),
    # User
    ('projects/<int:p_id>/users/create', UserCreate.as_view(), 'user-create'),
    ('projects/<int:p_id>/users/<int:u_id>/update', UserUpdate.as_view(), 'user-update'),
    # Member
    ('projects/<int:p_id>/members', MemberList.as_view(), 'member-list'),
    ('projects/<int:p_id>/members/create', MemberCreate.as_view(), 'member-create'),
    ('projects/<int:p_id>/members/<int:m_id>/delete', MemberDelete.as_view(), 'member-delete'),
]

urlpatterns = [path(url[0], url[1], name=url[2]) for url in urls]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('velo/', include('myapp.urls')),
]

myapp/models/assignee.py
from django.db import models


class Assignee(models.Model):
    """ Represents the relationship between a Task and a User. """
    task = models.ForeignKey(
        'Task',
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE
    )
    hours_worked = models.DecimalField(
        max_digits=5,
        decimal_places=1,
        default=0
    )

    class Meta:
        # Ensures that the assignees are unique for a task.
        unique_together = ('task', 'user')

myapp/models/member.py
from django.db import models

from ..choices import MemberRole
from ..utils import pretty_hour


class Member(models.Model):
    """ Represents the relationship between a Project and a User. """
    project = models.ForeignKey(
        'Project',
        on_delete=models.CASCADE,
        related_name='members'
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE
    )
    role = models.IntegerField(
        choices=MemberRole.choices,
        default=MemberRole.MEMBER
    )

    def log_time(self):
        """ Returns the total time worked by this member on this project. """
        return self.user.log_time(self.project)

    def get_log_time_display(self) -> str:
        """ Returns the string representation. """
        return pretty_hour(self.log_time())

    class Meta:
        # Ensures that the members are unique for a project.
        unique_together = ('project', 'user')

myapp/models/project.py
from django.db import models
from django.utils import timezone

from ..choices import ProjectStatus
from ..utils import Progress, pretty_date, pretty_hour


def get_default_project_end_date():
    return timezone.now() + timezone.timedelta(weeks=6)


class Project(models.Model):
    """ Represents a project. """
    name = models.CharField(
        max_length=255
    )
    start_date = models.DateTimeField(
        default=timezone.now
    )
    end_date = models.DateTimeField(
        default=get_default_project_end_date
    )
    status = models.IntegerField(
        choices=ProjectStatus.choices,
        default=ProjectStatus.NOT_STARTED
    )
    description = models.TextField(
        blank=True
    )
    team = models.ManyToManyField(
        'User',
        through='Member',
        blank=True,
        related_name='projects'
    )

    def is_complete(self) -> bool:
        """ Returns True if this project is complete. """
        return self.status == ProjectStatus.COMPLETED

    def point_progress(self) -> Progress:
        """ Returns the progress on the story points of this project. """
        sprints = [sprint.point_progress() for sprint in self.sprints.all()]
        return Progress(
            total=sum(progress.total for progress in sprints),
            completed=sum(progress.completed for progress in sprints)
        )

    def task_progress(self) -> Progress:
        """ Returns the progress on the tasks of this project. """
        sprints = [sprint.task_progress() for sprint in self.sprints.all()]
        return Progress(
            total=sum(progress.total for progress in sprints),
            completed=sum(progress.completed for progress in sprints)
        )

    def log_time(self) -> int:
        """ Returns the total time worked on this project. """
        return sum(sprint.log_time() for sprint in self.sprints.all())

    def get_start_date_display(self) -> str:
        """ Returns the string representation. """
        return pretty_date(self.start_date)

    def get_end_date_display(self) -> str:
        """ Returns the string representation. """
        return pretty_date(self.end_date)

    def get_log_time_display(self) -> str:
        """ Returns the string representation. """
        return pretty_hour(self.log_time())

    def __str__(self) -> str:
        """ Returns the string representation. """
        return self.name

myapp/models/tag.py
from django.db import models


class Tag(models.Model):
    """ Represents a tag. """
    name = models.CharField(max_length=25)

    def __str__(self) -> str:
        """ Returns the string representation. """
        return self.name

myapp/models/task.py
from django.db import models
from django.core import validators
from django.utils import timezone

from ..choices import TaskType, TaskPriority, TaskStatus
from ..utils import pretty_date, pretty_hour


def get_default_task_end_date():
    return timezone.now() + timezone.timedelta(days=3)


class Task(models.Model):
    """ Represents a task.
    Each task is linked to a sprint.
    Each task is related to a user through the concept of an assignee.
    """
    sprint = models.ForeignKey(
        'Sprint',
        on_delete=models.DO_NOTHING,
        related_name='tasks',
    )
    name = models.CharField(
        max_length=255
    )
    type = models.CharField(
        max_length=255,
        choices=TaskType.choices,
        default=TaskType.USER_STORY
    )
    start_date = models.DateTimeField(
        default=timezone.now
    )
    due_date = models.DateTimeField(
        default=get_default_task_end_date
    )
    story_points = models.IntegerField(
        default=5,
        validators=[
            validators.MinValueValidator(0),
            validators.MaxValueValidator(10)
        ]
    )
    priority = models.IntegerField(
        choices=TaskPriority.choices,
        default=TaskPriority.MEDIUM
    )
    status = models.IntegerField(
        choices=TaskStatus.choices,
        default=TaskStatus.NOT_STARTED
    )
    is_important = models.BooleanField(
        default=False
    )
    tags = models.ManyToManyField(
        'Tag',
        blank=True,
        related_name='tagged_tasks'
    )
    assignees = models.ManyToManyField(
        'User',
        through='Assignee',
        blank=True,
        related_name='assigned_tasks'
    )
    description = models.TextField(
        blank=True
    )

    def is_assigned_to(self, user) -> bool:
        """ Returns True if this task is assigned to a specific user. """
        return self.assignees.contains(user)

    def is_complete(self) -> bool:
        """ Returns True if this task is complete. """
        return self.status == TaskStatus.COMPLETED

    def log_time(self) -> float:
        """ Returns the total time worked on this task. """
        return sum(assignee.hours_worked for assignee in self.assignee_set.all())

    def get_start_date_display(self) -> str:
        """ Returns the string representation. """
        return pretty_date(self.start_date)

    def get_due_date_display(self) -> str:
        """ Returns the string representation. """
        return pretty_date(self.due_date)

    def get_story_points_display(self) -> str:
        """ Returns the string representation. """
        return str(self.story_points) + ' story points'

    def get_log_time_display(self) -> str:
        """ Returns the string representation. """
        return pretty_hour(self.log_time())

    def __str__(self) -> str:
        """ Returns the string representation. """
        return self.name

myapp/views/member.py
from django.views.generic import ListView, CreateView, DeleteView
from django.views.generic.edit import ContextMixin, FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, reverse, redirect
from django.db import IntegrityError

from ..models import Project, Member
from ..utils import pretty_form


class MemberMixin(LoginRequiredMixin, ContextMixin):
    model = Member
    pk_url_kwarg = 'm_id'
    kwargs = None
    project = None

    def dispatch(self, request, *args, **kwargs):
        """ Initialises the project attribute. """
        self.project = get_object_or_404(Project, id=self.kwargs['p_id'])
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        """ Returns the URL to go to after creating/editing/deleting. """
        return reverse('member-list', args=[self.project.id])

    def get_context_data(self, **kwargs):
        """ Appends the Project instance to the context. """
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        return context


class MemberFormMixin(MemberMixin, FormMixin):
    fields = '__all__'
    request = None

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields.pop('project')
        return pretty_form(form, user=self.request.user)

    def form_valid(self, form):
        """ Sets this member's project to the project. """
        form.instance.project = self.project
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('user', "This user is already a member of this project.")
            return self.form_invalid(form)


# VIEWS -----------------------------------------------------------------------

class MemberList(MemberMixin, ListView):
    context_object_name = 'members'

    def get_queryset(self):
        """ Returns this project's users. """
        members = self.project.members.all()
        search_query = self.request.GET.get('search', '')
        if search_query:
            members = members.filter(user__username__contains=search_query)
        return members

    def get(self, request, *args, **kwargs):
        p_id = int(request.GET.get('project-id', -2))
        if p_id == -2:
            request.user.set_last_visited_project(self.project)
            return super().get(request, *args, **kwargs)
        elif p_id == -1:
            return redirect('project-list')
        else:
            return redirect(reverse('member-list', args=[p_id]))


class MemberCreate(MemberFormMixin, CreateView):
    pass


class MemberDelete(MemberMixin, DeleteView):

    def post(self, request, *args, **kwargs):
        """ Prevents non guests from deleting a member. """
        if not request.user.is_staff:
            return render(request, 'forbidden.html', status=403)
        return super().post(request, *args, **kwargs)

myapp/views/project.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy

from ..choices import SprintStatus
from ..models import Project, User
from ..utils import *


# MIXINS ----------------------------------------------------------------------

class ProjectMixin(LoginRequiredMixin):
    model = Project
    pk_url_kwarg = 'p_id'
    success_url = reverse_lazy('project-list')


class ProjectFormMixin(ProjectMixin, FormMixin):
    fields = '__all__'
    object = None
    request = None

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields.pop('team')
        return pretty_form(form, self.request.user)

    def form_valid(self, form):
        """ Adds the user who created the project to their project. """
        self.object = form.save()
        self.object.team.add(self.request.user, through_defaults={})
        return super().form_valid(form)


# VIEWS -----------------------------------------------------------------------

class ProjectList(ProjectMixin, ListView):
    context_object_name = 'projects'

    def get_queryset(self):
        """ Returns the current user's projects. """
        projects = self.request.user.projects.order_by('status')
        search_query = self.request.GET.get('search', '')
        if search_query:
            projects = projects.filter(name__icontains=search_query)
        return projects

    def get(self, request, *args, **kwargs):
        """ Clears the user's last visited project. """
        request.user.set_last_visited_project(None)
        return super().get(request, *args, **kwargs)


class ProjectDetail(ProjectMixin, DetailView):

    def get(self, request, *args, **kwargs):
        p_id = int(request.GET.get('project-id', -2))
        self.request.session['previous_page'] = self.request.path
        if p_id == -2:
            project = Project.objects.get(id=self.kwargs['p_id'])
            request.user.set_last_visited_project(project)
            return super().get(request, *args, **kwargs)
        elif p_id == -1:
            return redirect('project-list')
        else:
            return redirect(reverse('project-detail', args=[p_id]))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user: User = self.request.user
        project: Project = self.object
        sprints = project.sprints.all()
        sprint = sprints.filter(status=SprintStatus.ACTIVE).first()
        if sprint:
            # Add to context
            context['active_sprint'] = sprint
            context['user_progress'] = user.task_progress(project, sprint)
            context['user_log_time'] = user.get_log_time_display(project, sprint)
            context['todo'] = user.remaining_tasks(project, sprint)
            context['charts'] = [
                get_burndown_chart(sprint),
                get_sprint_vs_log_time_chart(sprints),
                get_user_vs_log_time_chart(sprint)
            ]
        return context


class ProjectCreate(ProjectFormMixin, CreateView):
    pass


class ProjectUpdate(ProjectFormMixin, UpdateView):
    pass


class ProjectDelete(ProjectMixin, DeleteView):

    def post(self, request, *args, **kwargs):
        """ Prevents non superusers from deleting a project. """
        if not request.user.is_superuser:
            return render(request, 'forbidden.html', status=403)
        return super().post(request, *args, **kwargs)

myapp/templates/myapp/member_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}New Member{% endblock %}

{% block main %}
    <div class='container p-5 my-5 border'>
        <form method='post'>
            <h2 class='mb-3'>New Member</h2>
            <p>Select an existing user to add to your project.</p>
            {% csrf_token %}
            {% bootstrap_form form %}
            <!-- Submit -->
            <input class='btn btn-primary'
                   type='submit'
                   value='Add'>
            <!-- Cancel -->
            <a class='btn btn-secondary text-white text-decoration-none'
               href='{% url 'member-list' project.id %}'>Cancel</a>
        </form>
    </div>
{% endblock %}

myapp/templates/myapp/member_list.html
{% extends 'base.html' %}

{% block title %}Team{% endblock %}

{% block main %}
    <div class='container my-5'>
        <!-- Description -->
        <h2 class='mb-3'>Your Team</h2>
        <p>View all registered users.</p>
        <p>Click on a user to view or edit its details.</p>
        <!-- Navigation -->
        <div class='d-flex flex-wrap'>
            <!-- Search Bar -->
            <div class='me-auto mb-2'>
                <form class='input-group' method='GET'>
                    <input class='form-control shadow-none'
                           type='text'
                           name='search'
                           aria-label='search'
                           value='{{ request.GET.search }}'
                           placeholder='Search for a user ... '
                           autofocus
                           onfocus='this.setSelectionRange(this.value.length,this.value.length);'>
                    <button class='btn btn-success'
                            type='submit'>Go
                    </button>
                    <a class='btn btn-secondary text-white text-decoration-none'
                       href='{% url 'member-list' project.id %}'>Clear</a>
                </form>
            </div>
            <!-- Add Existing User Button -->
            <div class='me-5 mb-2'>
                <a class='btn btn-primary'
                   href={% url 'member-create' project.id %}>Add Existing User</a>
            </div>
            <!-- Create New User Button -->
            <div class='me-5'>
                <a class='btn btn-primary'
                   href={% url 'user-create' project.id %}>Add New User</a>
            </div>
        </div>
        <!-- Table View -->
        <div class='table-responsive mt-3'>
            <table class='table table-hover'>
                <thead>
                <tr>
                    <th>Username</th>
                    <th>Display Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Log Time</th>
                    <th>Last Login</th>
                </tr>
                </thead>
                <tbody class='table-group-divider'>
                <!-- Rows -->
                {% for member in members %}
                    <tr style='cursor: pointer;'
                        onclick="window.location.href='{% url 'user-update' project.id member.user.id %}'">
                        <td>{{ member.user.get_username }}
                            {% if member.user.is_admin or member.user.is_superuser %}👮{% endif %}</td>
                        <td>{{ member.user.get_full_name }}</td>
                        <td>{{ member.user.email }}</td>
                        <td>{{ member.get_role_display }}</td>
                        <td>{{ member.get_log_time_display }}</td>
                        <td>{{ member.user.get_last_login_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/project_list.html
{% extends 'base.html' %}

{% block title %}Projects{% endblock %}

{% block style %}
    <style>
        .active {
            background-color: rgba(47, 140, 255, 1);
            color: white;
        }

        .active a {
            color: white;
        }

        .notstarted a {
            color: black
        }

        .completed {
            background-color: rgba(245, 245, 245, 0.4);
            color: rgba(0, 0, 0, 0.5);
        }

        .completed a {
            color: rgba(0, 0, 0, 0.5);
        }

        .card:hover {
            cursor: pointer;
            border-width: thick;
        }
    </style>
{% endblock %}

{% block main %}
    <div class='container mt-5 mb-5'>
        <!-- Description -->
        <h2 class='mb-3'>Your Projects</h2>
        <p>View your projects ordered by status.</p>
        <p>Click on a project to view or update its details.</p>
        <!-- Navigation -->
        <div class='d-flex flex-wrap'>
            <!-- Search Bar -->
            <div class='me-auto mb-2'>
                <form class='input-group' method='GET'>
                    <input class='form-control shadow-none'
                           type='text'
                           name='search'
                           aria-label='search'
                           value='{{ request.GET.search }}'
                           placeholder='Search for a project ... '
                           autofocus
                           onfocus='this.setSelectionRange(this.value.length,this.value.length);'>
                    <button class='btn btn-success'
                            type='submit'>Go
                    </button>
                    <a class='btn btn-secondary text-white text-decoration-none'
                       href='{% url 'project-list' %}'>Clear</a>
                </form>
            </div>
            <!-- Create Button -->
            <div class='me-5'>
                <a class='btn btn-primary'
                   href={% url 'project-create' %}>Create Project</a>
            </div>
        </div>
        <!-- Cards -->
        <div class='row'>
            {% for project in projects %}
                <div class='col-sm-4'>
                    <div class='card mt-3 {{ project.get_status_display|cut:' '|lower }}'
                         onclick="window.location.href='{% url 'project-update' project.id %}'">
                        <div class='card-body'>
                            <h5 class='card-title mb-3'>{{ project.name }}</h5>
                            <p class='card-text mb-2'>{{ project.get_status_display }}</p>
                            <p class='card-text mb-2'>
                                {{ project.get_start_date_display }} - {{ project.get_end_date_display }}
                            </p>
                            <p class='card-text mb-2'>
                                {{ project.point_progress.completed }}/{{ project.point_progress.total }}
                                story points achieved
                            </p>
                            <p class='card-text mb-2'>
                                {{ project.task_progress.completed }}/{{ project.task_progress.total }}
                                tasks completed
                            </p>
                            <p class='card-text'>{{ project.get_log_time_display }} logged</p>
                            <a class='card-link'
                               href='{% url 'project-detail' project.id %}'>Dashboard</a>
                            <a class='card-link'
                               href='{% url 'member-list' project.id %}'>Team</a>
                            <a class='card-link'
                               href='{% url 'sprint-list' project.id %}'>Sprints</a>
                            <a class='card-link'
                               href='{% url 'task-list' project.id %}'>Tasks</a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p></p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/sprint_board.html
{% extends 'base.html' %}

{% block title %}Scrum Board{% endblock %}

{% block main %}
    <div class='container my-5'>
        <!-- Description -->
        <h2 class='mb-3'>{{ sprint.name }}'s Scrum Board</h2>
        <p>View this sprint's tasks by status.</p>
        <p>Click on a task to view or edit its details.</p>
        <!-- Navigation -->
        <div class='d-flex flex-wrap'>
            <!-- Search Bar -->
            <div class='me-auto mb-2'>
                <form class='input-group' method='GET'>
                    <input class='form-control shadow-none'
                           type='text'
                           name='search'
                           aria-label='search'
                           value='{{ request.GET.search }}'
                           placeholder='Search for a task ... '
                           autofocus
                           onfocus='this.setSelectionRange(this.value.length,this.value.length);'>
                    <button class='btn btn-success'
                            type='submit'>Go
                    </button>
                    <a class='btn btn-secondary text-white text-decoration-none'
                       href='{% url 'sprint-board' project.id sprint.id %}'>Clear</a>
                </form>
            </div>
            <!-- Create Button -->
            <div class='me-5'>
                <a class='btn btn-primary'
                   href={% url 'task-create' project.id %}>Create Task</a>
            </div>
        </div>
        <!-- Columns -->
        <div class='row mt-4'>
            {% for status, tasks in status_to_tasks.items %}
                <div class='col-sm me-4'>
                    <h5>{{ status }}</h5>
                    <!-- Cards -->
                    {% for task in tasks %}
                        <div class='card text-bg-light my-3'
                             style='cursor: pointer;'
                             onclick="window.location.href='{% url 'task-update' project.id task.id %}'"
                             onmouseover="this.style.borderWidth='4px'"
                             onmouseout="this.style.borderWidth='1px'">
                            <div class="card-header">{{ task.name }}</div>
                            <div class='card-body'>
                                <p class='card-text'>Due: {{ task.get_due_date_display }}</p>
                                <p class='card-text'>Type: {{ task.get_type_display }}</p>
                                <p class='card-text'>
                                    {% if task.assignees.all %}Assignees:{% endif %}
                                    {% for assignee in task.assignees.all %}
                                        {{ assignee.first_name }}{% if not forloop.last %}, {% endif %}
                                    {% empty %}
                                        Unassigned
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/sprint_chart.html
{% extends 'base.html' %}

{% block title %}Burndown Chart{% endblock %}

{% block main %}
    <div class='container mt-5 mb-5'>
        <img class='img-fluid' src='data:image/png;base64,{{ chart }}' alt='burndown chart'>
    </div>
{% endblock %}

myapp/templates/myapp/task_list.html
{% extends 'base.html' %}

{% block title %}Tasks{% endblock %}

{% block main %}
    <div class='container mt-5 mb-5'>
        <!-- Description -->
        <h2 class='mb-3'>{{ project.name }}'s Tasks</h2>
        <p>View your tasks ordered by due date descending.</p>
        <p>Click on a task to view or edit its details.</p>
        <!-- Navigation -->
        <div class='d-flex flex-wrap'>
            <!-- Search Bar -->
            <div class='me-auto mb-2'>
                <form class='input-group' method='GET'>
                    <input class='form-control shadow-none'
                           type='text'
                           name='search'
                           aria-label='search'
                           value='{{ request.GET.search }}'
                           placeholder='Search for a task ... '
                           autofocus
                           onfocus='this.setSelectionRange(this.value.length,this.value.length);'>
                    <button class='btn btn-success'
                            type='submit'>Go
                    </button>
                    <a class='btn btn-secondary text-white text-decoration-none'
                       href='{% url 'task-list' project.id %}'>Clear</a>
                </form>
            </div>
            <!-- Create Button -->
            <div class='me-5'>
                <a class='btn btn-primary'
                   href={% url 'task-create' project.id %}>Create Task</a>
            </div>
        </div>
        <!-- Table View -->
        <div class='table-responsive mt-3'>
            <table class='table table-hover'>
                <thead>
                <tr>
                    <th>Task Name</th>
                    <th>Sprint</th>
                    <th>Priority</th>
                    <th>Due Date</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Estimation</th>
                    <th>Log Time</th>
                </tr>
                </thead>
                <tbody class='table-group-divider'>
                <!-- Rows -->
                {% for task in tasks %}
                    <tr style='cursor: pointer;'
                        onclick="window.location.href='{% url 'task-update' project.id task.id %}'">
                        <td>{{ task.name }}
                            {% if task.is_important %}
                                <span class='badge bg-danger ms-1'>!</span>
                            {% endif %}
                        </td>
                        <td>{{ task.sprint }} </td>
                        <td>{{ task.get_priority_display }}</td>
                        <td>{{ task.get_due_date_display }}</td>
                        <td>{{ task.get_type_display }} </td>
                        <td>{{ task.get_status_display }}</td>
                        <td>{{ task.get_story_points_display }}</td>
                        <td>{{ task.get_log_time_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}